// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7X5j-uDMLjnGHeYth2yA_2pgzfy8Eplc',
    appId: '1:394490348413:web:d9ab0c5398dc68f82d4214',
    messagingSenderId: '394490348413',
    projectId: 'mobile-app-development-1a585',
    authDomain: 'mobile-app-development-1a585.firebaseapp.com',
    databaseURL: 'https://mobile-app-development-1a585-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-app-development-1a585.firebasestorage.app',
    measurementId: 'G-G5XJESD3YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRjYQzMJD_pP3sUPFsd8Jxlvs2mdQkaB4',
    appId: '1:394490348413:android:c800a3f8e4f173c02d4214',
    messagingSenderId: '394490348413',
    projectId: 'mobile-app-development-1a585',
    databaseURL: 'https://mobile-app-development-1a585-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-app-development-1a585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNosZ-gK_FblO_WJcVqZYUSqw8Me-biis',
    appId: '1:394490348413:ios:1a5bb685068851fb2d4214',
    messagingSenderId: '394490348413',
    projectId: 'mobile-app-development-1a585',
    databaseURL: 'https://mobile-app-development-1a585-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-app-development-1a585.firebasestorage.app',
    iosBundleId: 'com.example.warehouseManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNosZ-gK_FblO_WJcVqZYUSqw8Me-biis',
    appId: '1:394490348413:ios:1a5bb685068851fb2d4214',
    messagingSenderId: '394490348413',
    projectId: 'mobile-app-development-1a585',
    databaseURL: 'https://mobile-app-development-1a585-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-app-development-1a585.firebasestorage.app',
    iosBundleId: 'com.example.warehouseManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7X5j-uDMLjnGHeYth2yA_2pgzfy8Eplc',
    appId: '1:394490348413:web:f29daa396471fe002d4214',
    messagingSenderId: '394490348413',
    projectId: 'mobile-app-development-1a585',
    authDomain: 'mobile-app-development-1a585.firebaseapp.com',
    databaseURL: 'https://mobile-app-development-1a585-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-app-development-1a585.firebasestorage.app',
    measurementId: 'G-1H8GE34SBT',
  );
}
